---
- name: Stop MariaDB service
  user: sanjai
  hosts: localhost
  become: yes
  tasks:
    - name: mariadb stopped and not running
      service:
        name: mariadb
        enabled: false
        state: inactive
