---
- name: Stop MariaDB service
  user: sanjai
  hosts: 
    - 192.168.0.165
  become: yes
  tasks:
    - name: mariadb stopped and not running
      service:
        name: mariadb
        enabled: false
        state: inactive
